/*Action Types*/

export const SAVE_EMAIL = "SAVE_EMAIL";
export const SAVE_SUBJECT = "SAVE_SUBJECT";
export const SAVE_MESSAGE = "SAVE_MESSAGE";
export const CLEAR_EMAIL_FORM = "CLEAR_EMAIL_FORM";

export const CHANGE_PORTFOLIO_STATE = "CHANGE_PORTFOLIO_STATE";

export const CHANGE_HEADING_SIZE = "CHANGE_HEADING_SIZE";
export const CLOSE_PORTFOLIO = "CLOSE_PORTFOLIO";

export const EXPAND_PORTFOLIO_DIV = "EXPAND_PORTFOLIO_DIV";
